BitWise.exe: driver.o bitarray.o set.o
	g++ driver.o bitarray.o set.o -o BitWise.exe
	
driver.o: driver.cpp
	g++ -c driver.cpp -o driver.o
	
#dictionary.o: dictionary.cpp
#	g++ -c dictionary.cpp -o dictionary.o
	
bitarray.o: bitarray.cpp
	g++ -c bitarray.cpp -o bitarray.o
	
set.o: set.cpp
	g++ -c set.cpp -o set.o
	
clean:
	rm *.o BitWise.exe
	
#To run makefile with extension or non-makefile name:
#make -f makefile.CARD
#     and
#make -f makefile.CARD clean