# Honor Pledge:
#
# I pledge that I have neither given not
# received any help on this assignment
#
# iaustin

War.exe: driverCard.o card.o standardWar.o
	g++ driverCard.o card.o standardWar.o -o War.exe
	
driverCard.o: driverCard.cpp
	g++ -c driverCard.cpp -o driverCard.o
	
card.o: card.cpp
	g++ -c card.cpp -o card.o
	
standardWar.o: standardWar.cpp
	g++ -c standardWar.cpp -o standardWar.o
	
clean:
	rm -f *.o War.exe